version: "3"

services:
  db-postgres-api-nodejs:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-api-nodejs"
    restart: always
    volumes:
      - ./banco-de-dados-api-nodejs:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  banco-de-dados-api-nodejs:
